version: "3"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres:
